namespace SoftSync.Presentation.Services;

public static class ActiveListeningQuizBank
{
    public static readonly IReadOnlyList<CommunicationQuizQuestion> Questions =
    [
        Q(1, "Trong giờ học, bạn nghe thấy giảng viên nói nhưng không nhớ nội dung. Điều gì đã xảy ra?", "In class, you hear the lecturer but cannot remember the content. What happened?", ["Bạn đã lắng nghe rất kỹ", "Bạn chỉ nghe âm thanh mà chưa tập trung xử lý", "Giảng viên chắc chắn nói sai", "Nội dung không cần ghi nhớ"], ["You listened very carefully", "You heard the sound without actively processing it", "The lecturer must have been wrong", "The content did not need to be remembered"], 1, 0),
        Q(2, "Bạn đang nghe bạn kể chuyện nhưng điện thoại liên tục báo tin nhắn. Bạn nên làm gì?", "Your phone keeps notifying you while a friend is talking. What should you do?", ["Vừa xem điện thoại vừa gật đầu", "Bảo bạn nói nhanh hơn", "Úp hoặc cất điện thoại và tập trung vào bạn", "Đọc hết tin nhắn rồi mới nghe tiếp"], ["Check the phone while nodding", "Ask your friend to speak faster", "Put the phone away and focus on your friend", "Finish reading every message before listening"], 2, 3),
        Q(3, "Một người bạn nói: ‘Dạo này mình rất áp lực.’ Phản hồi nào thể hiện sự thấu cảm?", "A friend says, ‘I have been under a lot of pressure.’ Which response shows empathy?", ["Ai cũng áp lực, đừng nghĩ nhiều", "Mình nghe đây. Điều gì đang khiến bạn mệt nhất?", "Bạn nên nghỉ học vài hôm", "Chắc tại bạn quản lý thời gian kém"], ["Everyone is stressed; do not overthink it", "I am listening. What has been the hardest part for you?", "You should skip class for a few days", "It is probably because you manage time poorly"], 1, 2),
        Q(4, "Sau khi nhận một yêu cầu dài, cách nào giúp xác nhận bạn đã hiểu đúng?", "After receiving a long request, how can you confirm that you understood it?", ["Làm ngay theo phần mình nhớ", "Nói ‘vâng’ để kết thúc", "Tóm tắt lại ý chính và hỏi người nói xác nhận", "Nhờ người khác tự đoán yêu cầu"], ["Act immediately on what you remember", "Say yes to end the conversation", "Summarize the main points and ask for confirmation", "Ask someone else to guess the request"], 2, 0),
        Q(5, "Bạn cùng nhóm nói ‘Mình ổn’ nhưng tránh ánh mắt và giọng buồn. Bạn nên làm gì?", "A teammate says ‘I am fine’ but avoids eye contact and sounds sad. What should you do?", ["Chỉ tin vào câu nói và bỏ qua", "Nhẹ nhàng hỏi thêm vì bạn nhận thấy họ có vẻ không ổn", "Nói trước nhóm rằng họ đang nói dối", "Ép họ kể ngay mọi chuyện"], ["Believe only the words and ignore it", "Gently check in because they do not seem okay", "Tell the group that they are lying", "Force them to explain everything now"], 1, 0),
        Q(6, "Giảng viên lặp lại một ý và viết nó lên bảng. Bạn nên hiểu đây là gì?", "The lecturer repeats an idea and writes it on the board. What does this likely signal?", ["Một ý quan trọng cần chú ý và ghi chép", "Một phần có thể bỏ qua", "Giảng viên đã quên mình vừa nói", "Tín hiệu để dùng điện thoại"], ["An important point to notice and record", "A section you can ignore", "The lecturer forgot what was said", "A signal to use your phone"], 0, 2),
        Q(7, "Bạn không hiểu hướng dẫn làm bài. Phản ứng lắng nghe chủ động là gì?", "You do not understand an assignment instruction. What is an active-listening response?", ["Tự đoán rồi làm", "Im lặng vì sợ bị đánh giá", "Hỏi cụ thể điểm chưa rõ và nhắc lại yêu cầu", "Chép bài của bạn khác"], ["Guess and continue", "Stay silent to avoid judgment", "Ask about the unclear point and restate the requirement", "Copy another student's work"], 2, 0),
        Q(8, "Bạn nghĩ mình đã biết người đối diện sắp nói gì. Bạn nên làm gì?", "You think you know what the other person will say. What should you do?", ["Ngắt lời và nói hộ", "Vẫn để họ nói hết rồi mới phản hồi", "Đổi chủ đề cho nhanh", "Chỉ nghe một nửa câu"], ["Interrupt and finish for them", "Still let them finish before responding", "Change the subject to save time", "Listen to only half the sentence"], 1, 3),
        Q(9, "Trong lúc người khác nói, bạn chỉ chuẩn bị câu phản biện trong đầu. Điều này gây ra gì?", "While someone speaks, you only prepare your rebuttal. What does this cause?", ["Giúp bạn thấu cảm hơn", "Khiến bạn dễ bỏ lỡ thông điệp và cảm xúc", "Luôn giúp cuộc nói chuyện ngắn hơn", "Không ảnh hưởng đến lắng nghe"], ["It improves empathy", "It makes you miss the message and emotions", "It always shortens the conversation", "It has no effect on listening"], 1, 3),
        Q(10, "Bạn dễ mất tập trung trong lớp. Lựa chọn chỗ ngồi nào phù hợp nhất?", "You are easily distracted in class. Which seat is most helpful?", ["Gần phía trước để dễ tương tác với giảng viên", "Cuối lớp cạnh cửa ra vào", "Cạnh nhóm bạn hay trò chuyện", "Bất kỳ đâu miễn có thể dùng điện thoại"], ["Near the front for easier interaction with the lecturer", "At the back near the door", "Next to friends who often chat", "Anywhere you can use your phone"], 0, 1),
        Q(11, "Ghi chú khi nghe giảng có lợi ích chính nào?", "What is a main benefit of taking notes while listening?", ["Ghi lại mọi từ mà không cần hiểu", "Duy trì tập trung và lưu các ý chính", "Thay thế hoàn toàn việc lắng nghe", "Giúp không cần ôn lại"], ["Record every word without understanding", "Maintain focus and capture key ideas", "Completely replace listening", "Remove the need to review"], 1, 0),
        Q(12, "Bạn không đồng ý với quan điểm của người nói. Cách lắng nghe tốt nhất là gì?", "You disagree with the speaker. What is the best listening approach?", ["Phán xét họ ngay", "Nghe để hiểu góc nhìn trước khi nêu ý kiến", "Im lặng nhưng không nghe", "Tìm lỗi cá nhân của họ"], ["Judge them immediately", "Listen to understand their viewpoint before responding", "Stay silent without listening", "Look for personal faults"], 1, 2),
        Q(13, "Một thành viên ít nói trong cuộc họp nhóm. Nhóm trưởng nên làm gì?", "A member speaks very little in a group meeting. What should the leader do?", ["Kết luận rằng bạn ấy không có ý tưởng", "Mời bạn ấy chia sẻ và cho đủ thời gian trả lời", "Bỏ qua để họp nhanh hơn", "Hỏi dồn dập trước cả nhóm"], ["Assume they have no ideas", "Invite them to share and allow enough response time", "Ignore them to finish faster", "Question them rapidly in front of everyone"], 1, 3),
        Q(14, "Trong cuộc gọi trực tuyến, âm thanh bị ngắt quãng. Bạn nên phản hồi thế nào?", "Audio breaks up during an online call. How should you respond?", ["Giả vờ đã nghe rõ", "Nói rõ đoạn bị mất và nhờ người nói lặp lại", "Tự suy đoán toàn bộ", "Rời cuộc gọi không báo"], ["Pretend you heard clearly", "State which part was lost and ask for it to be repeated", "Guess the entire message", "Leave without notice"], 1, 2),
        Q(15, "Khi nhận góp ý về bài làm, hành động nào giúp bạn hiểu đúng nhất?", "When receiving feedback on your work, which action best ensures understanding?", ["Giải thích để tự bảo vệ ngay", "Nghe hết, hỏi ví dụ cụ thể và tóm tắt điều cần sửa", "Chỉ ghi nhớ lời khen", "Tranh luận từng câu"], ["Defend yourself immediately", "Listen fully, ask for examples, and summarize what to improve", "Remember only the praise", "Argue with every sentence"], 1, 0),
        Q(16, "Cuối buổi họp, cách nào tránh hiểu nhầm nhiệm vụ?", "At the end of a meeting, how can you avoid misunderstanding tasks?", ["Mọi người tự nhớ phần của mình", "Tóm tắt người phụ trách, việc cần làm và thời hạn", "Chờ đến sát hạn mới hỏi", "Chỉ ghi lại việc của trưởng nhóm"], ["Let everyone remember their own part", "Summarize owners, tasks, and deadlines", "Wait until the deadline to ask", "Record only the leader's tasks"], 1, 0),
        Q(17, "Người nói dùng từ chưa quen do khác biệt vùng miền. Bạn nên làm gì?", "The speaker uses an unfamiliar regional expression. What should you do?", ["Cười cách nói của họ", "Lịch sự hỏi ý nghĩa thay vì tự suy đoán", "Giả vờ hiểu", "Yêu cầu họ đừng nói nữa"], ["Laugh at their way of speaking", "Politely ask what it means instead of assuming", "Pretend to understand", "Ask them to stop speaking"], 1, 2),
        Q(18, "Bạn của bạn kể một vấn đề nhưng chưa chắc muốn được khuyên. Bạn nên làm gì trước?", "A friend shares a problem but may not want advice. What should you do first?", ["Đưa giải pháp ngay", "Hỏi họ muốn được lắng nghe hay cùng tìm giải pháp", "Kể vấn đề của mình", "Nói họ đang suy nghĩ quá nhiều"], ["Give solutions immediately", "Ask whether they want listening or help finding solutions", "Tell your own problem", "Say they are overthinking"], 1, 0),
        Q(19, "Trong tranh luận, người đối diện bắt đầu lớn tiếng. Phản ứng nào phù hợp?", "During a disagreement, the other person raises their voice. What is appropriate?", ["Lớn tiếng hơn", "Giữ bình tĩnh, xác nhận mối lo và đề nghị nói lần lượt", "Bỏ đi không nói gì", "Chế giễu cảm xúc của họ"], ["Speak even louder", "Stay calm, acknowledge the concern, and suggest taking turns", "Walk away without saying anything", "Mock their emotions"], 1, 2),
        Q(20, "Sau một thời gian dài, bạn quá mệt để tiếp tục lắng nghe hiệu quả. Bạn nên làm gì?", "After a long discussion, you are too tired to listen effectively. What should you do?", ["Tiếp tục giả vờ chú ý", "Xin nghỉ ngắn hoặc hẹn thời điểm phù hợp để tiếp tục", "Kết thúc bằng một câu trả lời bất kỳ", "Đổ lỗi người nói quá dài"], ["Keep pretending to pay attention", "Ask for a short break or arrange a suitable time to continue", "End with any random answer", "Blame the speaker for talking too long"], 1, 0)
    ];

    private static CommunicationQuizQuestion Q(int id, string vi, string en, string[] viOptions, string[] enOptions, int optimal, int neutral)
        => new(id, vi, en, viOptions, enOptions, optimal, neutral,
            "Phương án tối ưu thể hiện sự tập trung, xác nhận đúng thông tin và tôn trọng cảm xúc của người nói.",
            "The optimal response shows attention, confirms the message, and respects the speaker's feelings.");
}
