namespace SoftSync.Presentation.Services;

public sealed record CommunicationQuizQuestion(int Id, string Vi, string En, string[] OptionsVi, string[] OptionsEn, int Optimal, int Neutral, string FeedbackVi, string FeedbackEn);

public static class CommunicationQuizBank
{
    public static readonly IReadOnlyList<CommunicationQuizQuestion> Questions =
    [
        Q(1,"Một bạn trong nhóm chưa làm xong phần việc, khiến nhóm có nguy cơ trễ hạn. Bạn nhắn gì?","A teammate has not finished their work and the group may miss the deadline. What do you say?",["Bạn làm ăn kiểu gì mà trễ hết tiến độ vậy?","Thôi để mình làm luôn phần đó cho nhanh.","Phần này đang chậm. Bạn có gặp khó khăn gì để nhóm cùng hỗ trợ không?","Mình sẽ báo người phụ trách về việc bạn làm trễ."],2,1),
        Q(2,"Hai bạn không thoải mái với quán nước ồn ào được chọn để họp. Là người phụ trách, bạn nói gì?","Two members are uncomfortable with the noisy meeting place. What do you do?",["Mọi người chốt rồi, hai bạn ráng theo cho vui.","Hay mình chuyển sang chỗ yên tĩnh để tập trung, uống nước sau nhé?","Hủy họp, ai làm phần nấy qua tin nhắn.","Biểu quyết lại, bên đông hơn quyết định."],1,3),
        Q(3,"Cả nhóm chọn A nhưng bạn thấy phương án B có điểm hay hơn. Bạn làm gì?","The group chose A, but you see advantages in B. What do you do?",["Im lặng theo số đông.","Mọi người chọn A vì dễ, thật ra nó không tốt.","A cũng ổn, nhưng mình muốn nêu vài điểm hay của B để cùng chọn phương án tốt nhất.","Mình nghiêng về A, nhưng B có vài chỗ hay, mọi người muốn nghe không?"],2,3),
        Q(4,"Bạn nhận điểm thấp hơn mong đợi. Bạn email người chấm thế nào?","Your grade is lower than expected. How do you email the grader?",["Bài em tốt mà sao điểm thấp, xem lại giúp em.","Em đã xem lại bài và có thắc mắc. Thầy/cô giúp em biết phần nào bị trừ điểm được không ạ?","Thầy/cô chấm khó quá, em muốn chấm lại.","Cho em làm bài khác để gỡ điểm được không ạ?"],1,3),
        Q(5,"Bạn học giải thích khá dài một vấn đề bạn đã biết. Bạn làm gì?","A classmate explains at length something you already know. What do you do?",["Chuẩn bị câu trả lời và nói ngay khi họ ngừng.","Xem điện thoại trong lúc nghe.","Nghe hết, nhắc lại ý chính để xác nhận rồi mới nêu ý kiến.","Liên tục nói ‘hiểu rồi’ để họ nói nhanh hơn."],2,0),
        Q(6,"Bạn muốn xin 15–20 phút trao đổi với người có kinh nghiệm. Bạn nhắn thế nào?","You want a 15–20 minute career conversation with an experienced person. What do you write?",["Chào anh/chị, em đang tìm hiểu lĩnh vực này. Anh/chị có thể dành 15–20 phút chia sẻ kinh nghiệm không ạ?","CHÀO ANH/CHỊ, EM MUỐN HỎI KINH NGHIỆM GẤP.","Khi nào rảnh cho em xin ít phút nha.","Em gửi bài, anh/chị xem giúp em có ổn không."],0,2),
        Q(7,"Bạn bị nhận xét: ‘Phần này viết dở quá, đọc chẳng hiểu gì.’ Bạn phản ứng thế nào?","Someone says: ‘This part is terrible and impossible to understand.’ How do you respond?",["Bạn có làm được gì hay hơn không mà chê?","Mình hơi bối rối. Bạn chỉ rõ đoạn nào chưa rõ để mình sửa được không?","Vậy bạn tự viết lại đi.","Xin lỗi, để mình viết lại hết."],1,3),
        Q(8,"Một bài đăng trong nhóm có quan điểm hoàn toàn trái với bạn. Bạn xử lý sao?","A group post presents a view completely opposite to yours. What do you do?",["Bình luận dài để chỉ trích người đăng.","Báo cáo để gỡ bài.","Lờ đi để tránh phiền phức.","Phản hồi ôn hòa, nêu lý lẽ và tôn trọng góc nhìn khác."],3,2),
        Q(9,"Bạn làm mất tệp bài chính sát giờ nộp. Bạn báo nhóm thế nào?","You lose the main project file near the deadline. What do you tell the group?",["Máy lỗi nên mất hết, trễ là do máy.","Mình xin lỗi vì không lưu tệp. Mình chịu trách nhiệm, làm lại ngay và nhờ mọi người kiểm tra.","Tệp mất rồi, mắng cũng không giải quyết được.","Im lặng và tự làm lại."],1,2),
        Q(10,"Bạn cần báo lỗi kỹ thuật cho thành viên không rành kỹ thuật. Bạn nói thế nào?","You need to explain a technical issue to a non-technical teammate. What do you say?",["Dùng nguyên thuật ngữ chuyên môn.","Có lỗi kỹ thuật nhỏ, tụi mình đang sửa.","Lỗi ở phần hiển thị dữ liệu; đã tìm ra nguyên nhân và sẽ sửa xong trước ngày mai.","Lỗi code, bạn không cần hiểu đâu."],2,1),
        Q(11,"Đang thuyết trình thì một bạn chen ngang hỏi dồn dập. Bạn xử lý thế nào?","Someone interrupts your presentation with rapid questions. What do you do?",["Nói to lấn át.","Hoảng và quên nội dung.","Cảm ơn câu hỏi, xin nói hết phần này rồi dành thời gian trả lời kỹ.","Trả lời ngay rồi vội nói tiếp."],2,3),
        Q(12,"Phần bài của một bạn khá lộn xộn. Bạn góp ý thế nào?","A teammate's work is hard to follow. How do you give feedback?",["Rối như mớ bòng bong, ai hiểu nổi.","Phần này hơi khó theo dõi. Sắp xếp theo từng bước sẽ dễ hiểu hơn, bạn nghĩ sao?","Phần này tệ, chắc bị trừ điểm cả nhóm.","Để mình làm lại cho."],1,3),
        Q(13,"Nhóm sẽ đến muộn 10 phút vì xe hỏng. Bạn báo thế nào?","Your group will be ten minutes late due to a breakdown. What do you say?",["Giải thích rất dài về sự cố.","Nhóm em xin phép đến trễ khoảng 10 phút vì xe hỏng, xin lỗi vì sự bất tiện ạ.","Em trễ 10 phút nha thầy/cô.","Không báo, đến rồi giải thích."],1,2),
        Q(14,"Người chấm nói thiếu số liệu nhưng chúng nằm trong tệp đính kèm khác. Bạn phản hồi sao?","The grader says data is missing, but it is in another attachment. How do you respond?",["Em nộp đủ rồi, xem lại kỹ giúp em.","Xin lỗi rồi gửi lại tệp, không giải thích.","Cảm ơn phản hồi. Có thể tên tệp chưa rõ; số liệu ở Bao_cao_2.xlsx, em gửi lại ngay ạ.","Không trả lời."],2,1),
        Q(15,"Bạn điều phối buổi họp nhóm. Bạn quản lý thời gian thế nào?","You facilitate a group meeting. How do you manage time?",["Chờ người đến muộn 15 phút.","Gửi nội dung trước, bắt đầu đúng giờ, chia thời gian và nhắc nhẹ khi lan man.","Để mọi người nói tự do.","Kéo dài thêm một tiếng."],1,2),
        Q(16,"Đề xuất của bạn bị hiểu thành ‘làm qua loa’. Bạn phản hồi thế nào?","Your proposal is misrepresented as ‘doing careless work.’ How do you respond?",["Ừ, làm sơ sài cho nhanh.","Bạn cố tình bóp méo ý mình.","Ý mình là làm thật tốt phần chính trước. Hãy cùng xem phần nào cần ưu tiên.","Im lặng vì bất đồng lớn."],2,1),
        Q(17,"Bạn học nói mất ngủ, quá tải và không tập trung. Bạn phản hồi thế nào?","A classmate says they are sleep-deprived and overwhelmed. How do you respond?",["Ai cũng stress, ráng chịu.","Ngủ sớm và tập thể dục là hết.","Mình lo cho bạn. Nhóm có thể san sẻ việc để bạn nghỉ vài ngày không?","Hèn gì bạn làm chậm, ảnh hưởng cả nhóm."],2,1),
        Q(18,"Một thành viên thường im lặng vì quen lắng nghe hơn nói. Là nhóm trưởng, bạn làm gì?","A quiet member prefers listening to speaking. As leader, what do you do?",["Cho rằng bạn ấy lười.","Hỏi trước nhóm tại sao không nói.","Trao đổi riêng và tạo cách đóng góp khác như viết hoặc nhắn trước.","Bỏ qua để kịp tiến độ."],2,3),
        Q(19,"Bạn được nhờ làm hộ thuyết trình nhưng đang ôn thi ngày mai. Bạn từ chối thế nào?","A teammate asks you to do their presentation while you are studying for tomorrow's exam. How do you decline?",["Bạn lười vừa thôi.","Mình đang ôn thi nên không thể làm giúp. Bạn làm sau khi xong việc riêng được không?","Đưa đây mình làm.","Không trả lời."],1,2),
        Q(20,"Trong tranh luận, một bạn lớn tiếng nói ý bạn sẽ làm hỏng dự án. Bạn phản ứng sao?","During a debate, someone shouts that your idea will ruin the project. How do you respond?",["Lớn tiếng đáp trả.","Giữ bình tĩnh, ghi nhận lo lắng và hỏi rõ phần nào đáng lo để cùng xem lại.","Bỏ ra ngoài.","Im lặng đồng ý cho yên."],1,3)
    ];

    private static CommunicationQuizQuestion Q(int id, string vi, string en, string[] viOptions, int optimal, int neutral)
        => new(id, vi, en, viOptions, viOptions, optimal, neutral,
            "Phương án tối ưu tập trung vào sự bình tĩnh, tôn trọng và cùng giải quyết vấn đề.",
            "The optimal response stays calm, respectful, and focused on solving the problem together.");
}
