namespace SoftSync.Presentation.Services;

public static class TimeManagementQuizBank
{
    public static readonly IReadOnlyList<CommunicationQuizQuestion> Questions =
    [
        Q(1, "Điều gì thường được xem là \"kẻ thù\" lớn nhất cản trở việc quản lý thời gian hiệu quả?", "What is often considered the biggest enemy of effective time management?", ["Thiếu ngủ", "Sự trì hoãn", "Lịch học hoặc làm việc quá dày", "Các hoạt động ngoại khóa"], ["Lack of sleep", "Procrastination", "An overloaded study or work schedule", "Extracurricular activities"], 1, 2),
        Q(2, "Một lý do tâm lý phổ biến khiến người ta trì hoãn nhiệm vụ khó là gì?", "What is a common psychological reason people delay difficult tasks?", ["Quên hạn nộp", "Thấy nhiệm vụ quá dễ", "Sợ thất bại hoặc làm không đủ tốt", "Muốn thử thách bản thân vào phút chót"], ["Forgetting the deadline", "Finding the task too easy", "Fear of failure or not doing well enough", "Wanting a last-minute challenge"], 2, 0),
        Q(3, "Việc trì hoãn kéo dài có thể dẫn đến điều gì?", "What can prolonged procrastination lead to?", ["Tăng tính sáng tạo", "Rèn khả năng chịu áp lực", "Bỏ lỡ mục tiêu, căng thẳng và lo âu", "Giúp nhận ra việc không quan trọng"], ["More creativity", "Better pressure tolerance", "Missed goals, stress, and anxiety", "Recognizing unimportant work"], 2, 3),
        Q(4, "Khác biệt lớn nhất về quản lý thời gian giữa phổ thông và đại học hoặc đi làm là gì?", "What is the biggest time-management difference between school and university or work?", ["Ở phổ thông phần lớn lịch do người khác sắp xếp; càng lớn càng phải tự chủ động", "Ở phổ thông có nhiều thời gian rảnh hơn", "Ở phổ thông phải tự lên kế hoạch mọi việc", "Không có khác biệt đáng kể"], ["At school others largely arrange your schedule; later you must plan independently", "School students have more free time", "School students must plan everything alone", "There is no meaningful difference"], 0, 1),
        Q(5, "Bước đầu tiên để ước lượng chính xác thời gian hoàn thành nhiệm vụ là gì?", "What is the first step in accurately estimating task duration?", ["Hỏi người khác họ mất bao lâu", "Đọc và hiểu yêu cầu, độ dài và độ phức tạp", "Dành đúng một giờ cho mọi việc", "Vừa làm vừa chờ đến khi xong"], ["Ask how long others took", "Understand the requirements, length, and complexity", "Assign exactly one hour to every task", "Start and wait to see when it ends"], 1, 0),
        Q(6, "Chiến thuật Ba việc quan trọng nhất mỗi ngày mang lại lợi ích gì?", "What is the benefit of the Daily Top Three strategy?", ["Làm ba việc rồi nghỉ cả ngày", "Xác định và hoàn thành ba nhiệm vụ quan trọng nhất mỗi ngày", "Chia ngày thành ba phần bằng nhau", "Ghi nhớ ba sự kiện để kiểm tra"], ["Do three tasks and rest all day", "Identify and complete the three most important daily tasks", "Divide the day into three equal parts", "Memorize three events for a test"], 1, 2),
        Q(7, "Kỹ thuật Pomodoro giúp giảm mệt mỏi bằng cách nào?", "How does the Pomodoro technique reduce fatigue?", ["Làm ba giờ rồi nghỉ một giờ", "Làm theo phiên ngắn, thường 25 phút, xen kẽ nghỉ 3–5 phút", "Vừa làm vừa ăn", "Làm xong toàn bộ mới nghỉ"], ["Work three hours then rest one", "Use short sessions, usually 25 minutes, with 3–5 minute breaks", "Eat while working", "Rest only after everything is finished"], 1, 0),
        Q(8, "Theo chiến lược Eat the Frog, bạn nên làm gì đầu tiên?", "According to Eat the Frog, what should you do first?", ["Việc dễ nhất", "Việc thích nhất", "Nhiệm vụ lớn hoặc khó chịu mà bạn hay né tránh", "Trả lời tin nhắn và email"], ["The easiest task", "Your favorite task", "The large or unpleasant task you tend to avoid", "Messages and email"], 2, 0),
        Q(9, "Ma trận Eisenhower sắp xếp ưu tiên dựa trên hai yếu tố nào?", "Which two factors does the Eisenhower Matrix use?", ["Khó và dễ", "Thời gian và chi phí", "Quan trọng và khẩn cấp", "Yêu cầu từ nhiều phía"], ["Difficulty and ease", "Time and cost", "Importance and urgency", "Requests from different people"], 2, 1),
        Q(10, "Nhiệm vụ giá trị lớn có hạn chót sáng mai thuộc nhóm nào trong Ma trận Eisenhower?", "In the Eisenhower Matrix, where does a high-value task due tomorrow morning belong?", ["Quan trọng nhưng không khẩn cấp", "Khẩn cấp và quan trọng, cần làm ngay", "Khẩn cấp nhưng không quan trọng", "Không khẩn cấp và không quan trọng"], ["Important but not urgent", "Urgent and important: do it now", "Urgent but not important", "Neither urgent nor important"], 1, 0),
        Q(11, "Cách thông minh để tránh quá tải với một dự án lớn là gì?", "What is a smart way to avoid overload on a large project?", ["Thức trắng đêm", "Chia nhỏ dự án và phân bổ trong tuần", "Đợi sát hạn để có cảm hứng", "Làm kết luận trước"], ["Work all night", "Break it into smaller tasks distributed across the week", "Wait for deadline pressure", "Write the conclusion first"], 1, 3),
        Q(12, "Cách hiệu quả nhất để hạn chế xao nhãng từ điện thoại khi học là gì?", "What is the most effective way to limit phone distraction while studying?", ["Bật tivi làm tiếng nền", "Úp điện thoại trước mặt", "Cất điện thoại ngoài tầm mắt hoặc sang phòng khác", "Vừa học vừa trả lời nhanh"], ["Turn on the television", "Keep the phone face down nearby", "Put the phone out of sight or in another room", "Reply quickly while studying"], 2, 1),
        Q(13, "Vì sao làm nhiều việc cùng lúc thường không hiệu quả?", "Why is multitasking usually ineffective?", ["Tốn điện", "Não không xử lý tốt nhiều luồng phức tạp cùng lúc nên chất lượng giảm", "Làm bài quá nhanh", "Khiến phim kém thú vị"], ["It uses electricity", "The brain handles multiple complex streams poorly, reducing quality", "It makes work too fast", "It makes movies less enjoyable"], 1, 2),
        Q(14, "Nhận biết nhịp sinh học của bản thân có tác dụng gì?", "How does knowing your biological rhythm help?", ["Xin đổi giờ học", "Chọn khung giờ tập trung và nhiều năng lượng nhất để làm việc khó", "Có lý do ngủ nướng", "Ăn ngon hơn"], ["Request schedule changes", "Choose your most focused, energetic time for difficult work", "Justify sleeping late", "Improve appetite"], 1, 0),
        Q(15, "Chữ T trong nguyên tắc SMART có ý nghĩa gì?", "What does T mean in SMART goals?", ["Thực hiện cùng lúc", "Đo bằng bài kiểm tra", "Có thời hạn cụ thể", "Tốn nhiều thời gian"], ["Done simultaneously", "Measured by a test", "Having a specific deadline", "Taking a long time"], 2, 1),
        Q(16, "Một cách tốt để tận dụng lại quỹ thời gian bận rộn là gì?", "What is a good way to reclaim time in a busy schedule?", ["Bỏ ăn và ngủ", "Dùng khoảng thời gian chết để làm việc nhỏ hoặc ôn nhanh", "Xin nghỉ vài buổi", "Làm hai việc phức tạp cùng lúc"], ["Skip meals and sleep", "Use waiting time for a small task or quick review", "Take several days off", "Do two complex tasks simultaneously"], 1, 2),
        Q(17, "Vì sao học nhồi nhét cả đêm trước kỳ thi gây hậu quả xấu?", "Why is all-night cramming harmful?", ["Phải uống cà phê", "Gây căng thẳng, thiếu ngủ, quá tải và giảm ghi nhớ dài hạn", "Học kiến thức ngoài đề", "Giảng viên không hài lòng"], ["It requires coffee", "It causes stress, sleep loss, overload, and poor long-term retention", "It covers material outside the test", "It displeases the lecturer"], 1, 0),
        Q(18, "Nên làm gì khi phải học một khối lượng kiến thức lớn?", "What should you do when learning a large amount of material?", ["Học liên tục bốn giờ", "Đổi hoạt động, nghỉ ngắn hoặc tự hỏi sau mỗi 10–25 phút", "Nghe nhạc thật to", "Chỉ đọc phần tóm tắt"], ["Study four hours continuously", "Switch activity, pause briefly, or self-question every 10–25 minutes", "Play loud music", "Read only the summary"], 1, 3),
        Q(19, "Vì sao nên đưa ăn, ngủ và tập thể dục vào thời gian biểu?", "Why include meals, sleep, and exercise in a schedule?", ["Để lịch trông bận rộn", "Sức khỏe thể chất và tinh thần tốt giúp làm việc hiệu quả, bền vững", "Để thể hiện kỷ luật", "Để người khác thấy chăm chỉ"], ["To make the schedule look busy", "Physical and mental health support effective, sustainable work", "To display discipline", "To impress others"], 1, 2),
        Q(20, "Hiệu ứng Domino trong quản lý thời gian có nghĩa là gì?", "What does the Domino effect mean in time management?", ["Một trì hoãn nhỏ hoặc ước lượng sai có thể ảnh hưởng hàng loạt việc sau", "Xong một việc thì mọi việc khác tự xong", "Xếp sách như quân domino", "Giải trí trước khi học"], ["A small delay or bad estimate can disrupt many later tasks", "Completing one task completes all others", "Arrange books like dominoes", "Relax before studying"], 0, 1)
    ];

    private static CommunicationQuizQuestion Q(int id, string vi, string en, string[] viOptions, string[] enOptions, int optimal, int neutral)
        => new(id, vi, en, viOptions, enOptions, optimal, neutral,
            "Đáp án tối ưu áp dụng đúng nguyên tắc quản lý thời gian; phương án trung lập chỉ giải quyết được một phần vấn đề.",
            "The optimal answer correctly applies a time-management principle; the neutral choice only addresses part of the issue.");
}
