namespace SoftSync.Presentation.Services;

/// <summary>UI-only literal catalog. Never translates or modifies user-authored content.</summary>
public static class UiTextCatalog
{
    public static IReadOnlyList<(string En, string Vi)> Pairs { get; } = Array.AsReadOnly(new (string En, string Vi)[]
    {
        ("Courses", "Khóa học"),
        ("Courses · SoftSync", "Khóa học · SoftSync"),
        ("Loading courses...", "Đang tải khóa học..."),
        ("Video, caption, transcript and persistent learning progress.", "Video, phụ đề, bản chép lời và tiến độ học tập được lưu."),
        ("Lessons completed", "Bài học đã hoàn thành"),
        ("Final Quiz", "Bài kiểm tra cuối khóa"),
        ("Course Status", "Trạng thái khóa học"),
        ("Course Completed", "Đã hoàn thành khóa học"),
        ("Final quiz not passed yet. You may retry.", "Bạn chưa đạt bài kiểm tra cuối khóa. Bạn có thể làm lại."),
        ("Complete all required lessons and pass the final quiz.", "Hoàn thành tất cả bài học bắt buộc và đạt bài kiểm tra cuối khóa."),
        ("Complete all required lessons to finish this course.", "Hoàn thành tất cả bài học bắt buộc để hoàn tất khóa học."),
        ("Enroll / Continue", "Đăng ký / Học tiếp"),
        ("Captions are not available for this video.", "Video này chưa có phụ đề."),
        ("A transcript is not available for this video.", "Video này chưa có bản chép lời."),
        ("Lesson completed", "Đã hoàn thành bài học"),
        ("Mark lesson completed", "Đánh dấu hoàn thành bài học"),
        ("Retry Final Quiz", "Làm lại bài kiểm tra cuối khóa"),
        ("Open Final Quiz", "Mở bài kiểm tra cuối khóa"),
        ("Not required", "Không bắt buộc"),
        ("Not Started", "Chưa bắt đầu"),
        ("Pass", "Đạt"),
        ("Not Pass", "Chưa đạt"),
        ("PASS", "ĐẠT"),
        ("NOT PASS", "CHƯA ĐẠT"),
        ("Completed", "Đã hoàn thành"),
        ("In Progress", "Đang thực hiện"),
        ("In progress", "Đang học"),
        ("Enrollment saved.", "Đã lưu đăng ký học."),
        ("Could not enroll.", "Không thể đăng ký học."),
        ("Lesson progress saved.", "Đã lưu tiến độ bài học."),
        ("Enroll before completing a lesson.", "Hãy đăng ký khóa học trước khi hoàn thành bài học."),
        ("Teacher Studio", "Không gian giảng viên"),
        ("Teacher Studio · SoftSync", "Không gian giảng viên · SoftSync"),
        ("← Teacher Studio", "← Không gian giảng viên"),
        ("Courses & Inclusive Skill Challenge", "Khóa học và thử thách kỹ năng toàn diện"),
        ("My Courses", "Khóa học của tôi"),
        ("Create Course", "Tạo khóa học"),
        ("Course analytics", "Thống kê khóa học"),
        ("Title", "Tiêu đề"),
        ("Description", "Mô tả"),
        ("Skill ID", "Mã kỹ năng"),
        ("Thumbnail URL", "URL ảnh đại diện"),
        ("Thumbnail alt text", "Văn bản thay thế cho ảnh đại diện"),
        ("Or upload thumbnail (JPG, PNG, WEBP; max 5 MB)", "Hoặc tải ảnh đại diện (JPG, PNG, WEBP; tối đa 5 MB)"),
        ("Describe meaningful information in the image; leave empty only when it is decorative.", "Mô tả thông tin có ý nghĩa trong ảnh; chỉ để trống với ảnh trang trí."),
        ("Save", "Lưu"),
        ("Publish", "Xuất bản"),
        ("Lessons", "Các bài học"),
        ("Lesson", "Bài học"),
        ("Lesson title", "Tiêu đề bài học"),
        ("Video URL (.mp4/.webm)", "URL video (.mp4/.webm)"),
        ("Or upload video (max 200 MB)", "Hoặc tải video (tối đa 200 MB)"),
        ("Caption URL (.vtt)", "URL phụ đề (.vtt)"),
        ("Transcript", "Bản chép lời"),
        ("Add lesson", "Thêm bài học"),
        ("Quiz title", "Tiêu đề bài kiểm tra"),
        ("Create quiz", "Tạo bài kiểm tra"),
        ("Learner results", "Kết quả người học"),
        ("Quiz analytics", "Thống kê bài kiểm tra"),
        ("Add question", "Thêm câu hỏi"),
        ("AI creates an editable draft only.", "AI chỉ tạo bản nháp có thể chỉnh sửa."),
        ("Review every field and explicitly confirm the correct answer before saving.", "Kiểm tra mọi trường và xác nhận rõ đáp án đúng trước khi lưu."),
        ("Learning context for AI", "Ngữ cảnh bài học cho AI"),
        ("Paste only lesson content needed for this question; do not include student data.", "Chỉ dán nội dung bài học cần cho câu hỏi; không nhập dữ liệu học viên."),
        ("Generating draft...", "Đang tạo bản nháp..."),
        ("Generate with AI", "Tạo bằng AI"),
        ("Question type", "Loại câu hỏi"),
        ("Knowledge", "Kiến thức"),
        ("Scenario", "Tình huống"),
        ("Question", "Câu hỏi"),
        ("Explanation", "Giải thích"),
        ("Question image", "Ảnh câu hỏi"),
        ("Image alt text", "Văn bản thay thế cho ảnh"),
        ("Required when the question image communicates information needed to answer.", "Bắt buộc nếu ảnh chứa thông tin cần thiết để trả lời."),
        ("Answer options and correct answer", "Các lựa chọn và đáp án đúng"),
        ("Select the correct answer yourself to confirm the AI suggestion.", "Tự chọn đáp án đúng để xác nhận gợi ý của AI."),
        ("Upload complete.", "Tải lên hoàn tất."),
        ("Unsupported file type or file size.", "Định dạng hoặc dung lượng file không được hỗ trợ."),
        ("Could not save course because the server rejected the operation. Please reload and try again.", "Máy chủ từ chối lưu khóa học. Hãy tải lại trang và thử lại."),
        ("Confirm the correct answer yourself before saving this AI draft.", "Hãy tự xác nhận đáp án đúng trước khi lưu bản nháp AI."),
        ("Teacher Analytics", "Thống kê giảng viên"),
        ("Teacher Analytics · SoftSync", "Thống kê giảng viên · SoftSync"),
        ("Metrics use persisted enrollments and completed quiz attempts. In-progress attempts are reported separately.", "Thống kê sử dụng đăng ký đã lưu và các lượt làm bài hoàn tất. Lượt đang làm được thống kê riêng."),
        ("Loading analytics...", "Đang tải thống kê..."),
        ("Analytics are unavailable or you do not own this content.", "Không có thống kê hoặc nội dung không thuộc quyền sở hữu của bạn."),
        ("Enrollments", "Lượt đăng ký"),
        ("Completion rate", "Tỷ lệ hoàn thành"),
        ("Final quiz pass rate", "Tỷ lệ đạt bài cuối khóa"),
        ("Lesson completion among enrolled students", "Mức hoàn thành bài học của học viên đã đăng ký"),
        ("Completed students", "Học viên đã hoàn thành"),
        ("Score summary is calculated across all completed attempts.", "Tổng hợp điểm được tính từ tất cả lượt làm bài đã hoàn tất."),
        ("Participants (any attempt)", "Người tham gia (mọi lượt làm)"),
        ("Unique students (completed)", "Học viên đã hoàn tất"),
        ("Completed attempts", "Lượt đã hoàn tất"),
        ("In-progress attempts", "Lượt đang làm"),
        ("PASS attempts", "Lượt đạt"),
        ("NOT PASS attempts", "Lượt chưa đạt"),
        ("Pass rate", "Tỷ lệ đạt"),
        ("Average score", "Điểm trung bình"),
        ("Highest score", "Điểm cao nhất"),
        ("Lowest score", "Điểm thấp nhất"),
        ("Question accuracy", "Độ chính xác theo câu hỏi"),
        ("Correct rate by question, using completed attempts only", "Tỷ lệ đúng theo câu hỏi, chỉ tính lượt đã hoàn tất"),
        ("Attempts", "Lượt làm bài"),
        ("Correct", "Đúng"),
        ("Incorrect", "Sai"),
        ("Correct rate", "Tỷ lệ trả lời đúng"),
        ("Difficult question", "Câu hỏi khó"),
        ("Student results", "Kết quả học viên"),
        ("No completed student attempts.", "Chưa có lượt làm bài hoàn tất."),
        ("Latest and best result per student", "Kết quả mới nhất và tốt nhất của từng học viên"),
        ("Student", "Học viên"),
        ("Latest score", "Điểm mới nhất"),
        ("Best score", "Điểm tốt nhất"),
        ("Latest result", "Kết quả mới nhất"),
        ("Users", "Danh sách người dùng"),
        ("Roles", "Vai trò"),
        ("Teacher", "Giảng viên"),
        ("Admin", "Quản trị viên"),
        ("User", "Người dùng"),
        ("Protected", "Được bảo vệ"),
        ("Teacher account management · SoftSync", "Quản lý Teacher · SoftSync"),
        ("Teacher account management", "Quản lý tài khoản Teacher"),
        ("Only Teacher role membership is changed", "Chỉ thay đổi membership của role"),
        (". Existing Course/Quiz ownership is unchanged.", ". Ownership Course/Quiz hiện tại không bị thay đổi."),
        ("Loading users...", "Đang tải danh sách người dùng..."),
        ("Users and Teacher permissions", "Danh sách người dùng và quyền Teacher"),
        ("Actions", "Thao tác"),
        ("Assign Teacher", "Gán Teacher"),
        ("Remove Teacher", "Gỡ Teacher"),
        ("Only an Admin may manage another user's Teacher role.", "Chỉ Admin được quản lý quyền Teacher của người dùng khác."),
        ("User not found.", "Không tìm thấy người dùng."),
        ("Admin role membership cannot be changed here.", "Không thể thay đổi quyền Admin tại đây."),
        ("Quiz Result · SoftSync", "Kết quả bài kiểm tra · SoftSync"),
        ("Quiz History · SoftSync", "Lịch sử làm bài · SoftSync"),
        ("Quiz Review · SoftSync", "Xem lại đáp án · SoftSync"),
        ("Quiz Results · SoftSync", "Kết quả làm bài · SoftSync"),
        ("Quiz result", "Kết quả bài kiểm tra"),
        ("Loading result...", "Đang tải kết quả..."),
        ("Result not found", "Không tìm thấy kết quả"),
        ("The result does not exist, is incomplete, or does not belong to your account.", "Kết quả không tồn tại, chưa hoàn tất hoặc không thuộc tài khoản của bạn."),
        ("Score", "Điểm"),
        ("Result", "Kết quả"),
        ("Correct answers", "Câu trả lời đúng"),
        ("Incorrect answers", "Câu trả lời sai"),
        ("Started", "Bắt đầu"),
        ("Completed at", "Hoàn thành"),
        ("Review answers", "Review đáp án"),
        ("History", "Lịch sử"),
        ("Take another quiz", "Làm bài khác"),
        ("Attempt history", "Lịch sử làm bài"),
        ("Loading history...", "Đang tải lịch sử làm bài..."),
        ("Completed quiz attempts", "Các lần làm quiz đã hoàn thành"),
        ("You have not completed any quizzes yet.", "Bạn chưa hoàn thành bài kiểm tra nào."),
        ("View result", "Xem kết quả"),
        ("Learner quiz results", "Kết quả bài kiểm tra của người học"),
        ("Loading learner results...", "Đang tải kết quả người học..."),
        ("Quiz attempt results", "Kết quả các lần làm quiz"),
        ("Results are unavailable or you do not own this quiz.", "Không có kết quả hoặc bạn không sở hữu quiz này."),
        ("Cannot open review", "Không thể mở review"),
        ("The attempt is incomplete or you do not have access.", "Attempt chưa hoàn tất hoặc bạn không có quyền xem."),
        ("Loading review...", "Đang tải phần review..."),
        ("← Result", "← Kết quả"),
        ("Selected answer:", "Đáp án đã chọn:"),
        ("Correct answer:", "Đáp án đúng:"),
        ("Explanation:", "Giải thích:"),
        ("Scenario:", "Tình huống:"),
        ("AI explanation:", "AI giải thích thêm:"),
        ("Next practice steps", "Bước luyện tập tiếp theo"),
        ("Practice more", "Nội dung nên luyện thêm"),
        ("Strengths in this attempt", "Điểm mạnh trong bài này"),
        ("AI feedback", "Phản hồi AI"),
        ("Explaining...", "Đang giải thích..."),
        ("Explain this answer", "Giải thích câu trả lời này"),
        ("AI is unavailable. Review and results remain unchanged.", "AI hiện không khả dụng. Phần review và kết quả vẫn không thay đổi."),
        ("Generating feedback from the completed result...", "Đang tạo phản hồi từ kết quả đã hoàn tất..."),
        ("AI is unavailable or returned invalid feedback. Your score is unchanged.", "AI hiện không khả dụng hoặc phản hồi không hợp lệ. Kết quả chấm điểm vẫn được giữ nguyên."),
        ("Feedback generated; AI did not change the score or PASS/NOT PASS.", "Đã tạo phản hồi; AI không thay đổi điểm hoặc PASS/NOT PASS."),
        ("Inclusive Skill Challenge", "Thử thách kỹ năng toàn diện"),
        ("Inclusive Learning", "Học tập toàn diện"),
        ("Role-play", "Đóng vai"),
        ("Roadmap", "Lộ trình"),
        ("AI Assistant", "Trợ lý AI"),
        ("AI Feedback", "Nhận xét của AI"),
        ("Learning context", "Ngữ cảnh học tập"),
        ("Skip to main content", "Bỏ qua để đến nội dung chính"),
        ("An unhandled error has occurred.", "Đã xảy ra lỗi chưa được xử lý."),
        ("Reload", "Tải lại"),
        ("Access denied · SoftSync", "Không có quyền truy cập · SoftSync"),
        ("Access denied", "Bạn không có quyền truy cập"),
        ("Your account does not have access to this area.", "Tài khoản của bạn chưa có quyền sử dụng khu vực này."),
        ("Back to home", "Về trang chủ"),
        ("Sign in", "Đăng nhập"),
        ("Create account", "Tạo tài khoản"),
        ("Let’s get you back on track", "Hãy tiếp tục hành trình học tập"),
        ("Please return home, sign in, or create a free account to start learning.", "Hãy về trang chủ, đăng nhập hoặc tạo tài khoản miễn phí để bắt đầu học."),
        ("Something went wrong | SoftSync", "Đã xảy ra lỗi | SoftSync"),
        ("We couldn’t open that page right now. You can return home, sign in, or create a free account to start learning.", "Hiện không thể mở trang này. Bạn có thể về trang chủ, đăng nhập hoặc tạo tài khoản miễn phí để bắt đầu học."),
        ("Your account is still signed in and your saved progress is safe. Please return to your dashboard or roadmap.", "Bạn vẫn đang đăng nhập và tiến độ đã lưu được giữ nguyên. Hãy trở về trang học tập hoặc lộ trình."),
        ("CV Review", "Đánh giá CV"),
        ("CV Review — SoftSync", "Đánh giá CV — SoftSync"),
        ("AI evaluates CV content: clarity, skill evidence, experience/projects and missing information, with prioritized improvements rather than text extraction alone.", "AI đánh giá chất lượng nội dung CV: độ rõ ràng, bằng chứng kỹ năng, kinh nghiệm/dự án và thông tin còn thiếu; đề xuất cách sửa theo ưu tiên, không chỉ trích xuất văn bản."),
        ("This is not an ATS score or a hiring decision. Visual design cannot be assessed from extracted text. Please verify AI feedback.", "Không phải điểm ATS hay quyết định tuyển dụng. Không đánh giá thiết kế trực quan từ văn bản trích xuất. Hãy kiểm tra lại nhận xét của AI."),
        ("Upload a CV for review", "Tải CV để phân tích"),
        ("Job description / hiring requirements (optional)", "Mô tả công việc / yêu cầu tuyển dụng (không bắt buộc)"),
        ("Paste the role description and requirements to compare with your CV. Maximum 8,000 characters; do not include confidential information. The description is sent to AI and stored privately with the result. Leave blank for a general CV review.", "Dán mô tả vị trí và các yêu cầu để AI đối chiếu với CV. Tối đa 8.000 ký tự; không nhập thông tin mật. Mô tả sẽ gửi đến AI và lưu riêng tư cùng kết quả. Để trống để đánh giá CV chung."),
        ("Choose CV", "Chọn CV"),
        ("Review CV", "Phân tích CV"),
        ("Processing, please wait…", "Đang xử lý, vui lòng chờ…"),
        ("My reviews", "Phân tích của tôi"),
        ("No reviews yet.", "Chưa có phân tích nào."),
        ("Showing up to 100 latest reviews.", "Hiển thị tối đa 100 phân tích mới nhất."),
        ("Overall evaluation", "Đánh giá tổng quan"),
        ("Comparison with hiring requirements", "Đối chiếu yêu cầu tuyển dụng"),
        ("Job description used", "Mô tả tuyển dụng đã dùng"),
        ("This assessment uses evidence in the CV, not a hiring decision. “Not demonstrated” does not mean you lack the skill.", "Đánh giá dựa trên bằng chứng trong CV, không phải quyết định tuyển dụng. “Chưa có bằng chứng” không đồng nghĩa bạn không có kỹ năng."),
        ("Requirement coverage:", "Mức đáp ứng:"),
        ("Evidence / reasoning:", "Bằng chứng / lý do:"),
        ("Improvement suggestion:", "Gợi ý cải thiện:"),
        ("Not enough information.", "Chưa có đủ thông tin."),
        ("Section-by-section feedback", "Phân tích từng phần"),
        ("Review again", "Phân tích lại"),
        ("Delete CV and all reviews", "Xóa CV và tất cả phân tích"),
        ("Confirm deletion", "Xác nhận xóa"),
        ("Cancel", "Hủy"),
        ("Strengths", "Điểm mạnh"),
        ("Areas to improve", "Cần cải thiện"),
        ("Skills with evidence", "Kỹ năng có bằng chứng"),
        ("Missing or unclear information", "Thông tin thiếu hoặc chưa rõ"),
        ("Prioritized improvements", "Cách sửa theo thứ tự ưu tiên"),
        ("Supporting evidence", "Có bằng chứng đáp ứng"),
        ("Partial supporting evidence", "Có bằng chứng một phần"),
        ("Not demonstrated in this CV", "Chưa có bằng chứng trong CV"),
        ("No review belonging to your account was found.", "Không tìm thấy phân tích thuộc tài khoản của bạn."),
        ("Choose a PDF/DOCX file within the size limit.", "Chọn một file PDF/DOCX trong giới hạn dung lượng."),
        ("Review saved.", "Phân tích đã được lưu."),
        ("The CV no longer exists.", "CV không còn tồn tại."),
        ("New review saved; previous results are kept.", "Đã lưu phân tích mới; kết quả cũ vẫn được giữ."),
        ("CV and reviews deleted. This cannot be undone.", "Đã xóa CV và các phân tích. Thao tác này không thể hoàn tác."),
        ("Sign in again to access your CV.", "Vui lòng đăng nhập lại để truy cập CV."),
        ("Could not process the request. Please try again later.", "Không xử lý được yêu cầu. Vui lòng thử lại sau."),
        ("Job description must not exceed 8,000 characters.", "Mô tả tuyển dụng tối đa 8.000 ký tự."),
        ("Only valid PDF/DOCX files within the size limit are accepted.", "Chỉ nhận PDF/DOCX hợp lệ trong giới hạn dung lượng."),
        ("CV must contain 40–30,000 extractable text characters. Scanned PDFs are not supported yet.", "CV cần có 40–30.000 ký tự văn bản có thể trích xuất. PDF scan chưa được hỗ trợ."),
        ("AI returned an invalid result. Please try again.", "AI trả kết quả không hợp lệ. Hãy thử lại."),
        ("AI returned an invalid result.", "AI trả kết quả không hợp lệ."),
        ("AI is not configured. The CV was read but was not analyzed or saved.", "Dịch vụ AI chưa được cấu hình. CV đã được đọc nhưng chưa được phân tích hoặc lưu."),
        ("AI did not return a valid review (configuration, timeout or response error). Please try again later.", "AI chưa trả được phân tích hợp lệ (cấu hình, timeout hoặc phản hồi lỗi). Vui lòng thử lại sau."),
        ("The CV could not be read. Use a valid text PDF or DOCX with at most 30 pages and 30,000 characters.", "Không đọc được CV. Hãy dùng PDF có văn bản hoặc DOCX hợp lệ, tối đa 30 trang và 30.000 ký tự."),
        ("AI: configured (provider connectivity has not been verified).", "AI: đã cấu hình (chưa xác minh kết nối provider)."),
        ("AI: not configured. You can still try uploading and reading a CV; no analysis is saved without configuration.", "AI: chưa cấu hình. Bạn vẫn có thể thử upload và đọc CV; chưa lưu phân tích khi thiếu cấu hình."),
        ("Language of saved AI feedback", "Ngôn ngữ phản hồi AI đã lưu"),
        ("Switching language does not translate user content or saved AI results. Review again to generate feedback in the selected language.", "Đổi ngôn ngữ không dịch nội dung người dùng hoặc kết quả AI đã lưu. Phân tích lại để tạo phản hồi bằng ngôn ngữ đang chọn."),
        ("Published", "Đã xuất bản"),
        ("Draft", "Bản nháp"),
        ("Closed", "Đã đóng"),
        ("NotPass", "Chưa đạt yêu cầu"),
        ("Scenario-based", "Theo tình huống"),
        ("Audio", "Âm thanh"),
        ("Visual", "Hình ảnh"),
        ("Text", "Văn bản"),
        ("Male", "Nam"),
        ("Female", "Nữ"),
        ("Unspecified", "Chưa xác định"),
        ("N/A", "Không có dữ liệu"),
        ("Vietnamese captions", "Phụ đề tiếng Việt"),
        ("Counter", "Bộ đếm"),
        ("Click me", "Bấm vào đây"),
        ("Review", "Xem lại"),
        ("Video", "Video"),
        ("Script", "Kịch bản"),
        ("Attempt", "Lần làm bài"),
        ("Roles:", "Vai trò:"),
        ("Email", "Email"),
        ("Edit Course", "Chỉnh sửa khóa học"),
        ("Could not save course. Check the entered data and try again.", "Không lưu được khóa học. Kiểm tra dữ liệu và thử lại."),
        ("Course saved.", "Đã lưu khóa học."),
        ("Add at least one lesson before publishing.", "Thêm ít nhất một bài học trước khi xuất bản."),
        ("Course published.", "Đã xuất bản khóa học."),
        ("Could not save lesson.", "Không lưu được bài học."),
        ("Lesson saved.", "Đã lưu bài học."),
        ("Could not create quiz.", "Không tạo được bài kiểm tra."),
        ("Quiz created.", "Đã tạo bài kiểm tra."),
        ("Generating an editable draft. The quiz is not being saved or published.", "Đang tạo bản nháp chỉnh sửa được. Bài kiểm tra chưa được lưu hoặc xuất bản."),
        ("AI is unavailable or returned an invalid draft. You can continue creating the question manually, or retry.", "AI không khả dụng hoặc trả bản nháp không hợp lệ. Bạn vẫn có thể tạo câu hỏi thủ công hoặc thử lại."),
        ("Draft generated. Review and edit it, then select the correct answer yourself before saving.", "Đã tạo bản nháp. Kiểm tra, chỉnh sửa và tự chọn đáp án đúng trước khi lưu."),
        ("Enter one question, four options and select exactly one correct answer.", "Nhập một câu hỏi, bốn lựa chọn và chọn đúng một đáp án đúng."),
        ("Question saved.", "Đã lưu câu hỏi."),
        ("Quiz published.", "Đã xuất bản bài kiểm tra."),
        ("Teacher role assigned.", "Đã gán role Teacher."),
        ("Teacher role removed; the account retains the User role.", "Đã gỡ role Teacher; tài khoản vẫn giữ role User."),
        ("Generating feedback...", "Đang tạo phản hồi..."),
        ("Get personalized feedback", "Nhận phản hồi cá nhân hóa"),
        ("Back to dashboard", "Về trang học tập"),
        ("Open roadmap", "Mở lộ trình"),
        ("Review:", "Xem lại:"),
        ("Course:", "Khóa học:"),
        ("Quiz:", "Bài kiểm tra:"),
        ("Video lesson:", "Video bài học:"),
        ("Transcript for", "Bản chép lời cho"),
        ("percent complete", "phần trăm hoàn thành"),
        ("Current count:", "Số đếm hiện tại:"),
        ("Result:", "Kết quả:"),
        ("Reviewed at", "Đánh giá lúc"),
        ("Selected:", "Đã chọn:"),
        ("out of", "trên"),
        ("questions", "câu hỏi"),
        ("Quiz", "Bài kiểm tra"),
        ("Correct", "Đúng"),
        ("Incorrect", "Sai"),
        ("Please enter your full name.", "Vui lòng nhập họ tên."),
        ("Please enter your email.", "Vui lòng nhập email."),
        ("Please enter your email or phone number.", "Vui lòng nhập email hoặc số điện thoại."),
        ("Please enter your password.", "Vui lòng nhập mật khẩu."),
        ("Please enter a new password.", "Vui lòng nhập mật khẩu mới."),
        ("Please enter your phone number.", "Vui lòng nhập số điện thoại."),
        ("Please enter the code.", "Vui lòng nhập mã."),
        ("Invalid email address.", "Email không hợp lệ."),
        ("Invalid phone number.", "Số điện thoại không hợp lệ."),
        ("Passwords do not match.", "Mật khẩu nhập lại không khớp."),
        ("Password must contain between 6 and 100 characters.", "Mật khẩu phải từ 6 đến 100 ký tự."),
        ("Show or hide password", "Hiện hoặc ẩn mật khẩu"),
        ("QUIZ", "BÀI KIỂM TRA"),
        ("INBOX", "HỘP THƯ"),
        ("VIDEO 1 · SCRIPT", "VIDEO 1 · KỊCH BẢN"),
        ("GAME 5 · VOICE LAB", "TRÒ CHƠI 5 · LUYỆN GIỌNG NÓI"),
        ("Pacing", "Nhịp độ"),
        ("👥 Mentor", "👥 Cố vấn"),
        ("Speaking pace", "Tốc độ nói"),
        ("Articulation", "Độ rõ chữ"),
        ("Fillers & pauses", "Từ đệm & khoảng lặng"),
        ("Tone", "Tông giọng"),
        ("Natural and persuasive", "Tự nhiên và thuyết phục"),
        ("Fairly clear", "Khá rõ ràng"),
        ("Needs more practice", "Cần luyện thêm"),
        ("The total is provisional and does not include articulation.", "Điểm tổng tạm tính, chưa cộng mục độ rõ chữ."),
        ("The score is calculated from the transcript and audio signal.", "Điểm được tính từ transcript và tín hiệu âm thanh."),
        ("AI Configuration", "Cấu hình AI"),
        ("Unsupported provider.", "Provider không được hỗ trợ."),
        ("Use the official endpoint for this provider.", "Sử dụng endpoint chính thức của provider này."),
        ("Display name is required (maximum 120 characters).", "Tên hiển thị bắt buộc, tối đa 120 ký tự."),
        ("Model is required (maximum 200 characters, no whitespace).", "Model bắt buộc, tối đa 200 ký tự, không có khoảng trắng."),
        ("Invalid API key format.", "Định dạng API key không hợp lệ."),
        ("Enter a new key when changing provider.", "Nhập key mới khi đổi loại provider."),
        ("An enabled provider requires an API key.", "Provider đã bật cần có API key."),
        ("Activate another provider before disabling the default.", "Kích hoạt provider khác trước khi tắt provider đang dùng."),
        ("Only enabled, configured providers can be active.", "Chỉ provider đã bật và có key mới được kích hoạt."),
        ("Configuration not found.", "Không tìm thấy cấu hình."),
        ("Configuration changed. Reload and try again.", "Cấu hình đã thay đổi. Tải lại và thử lại."),
        ("Configuration could not be saved. Reload and try again.", "Không lưu được cấu hình. Tải lại và thử lại."),
    });
    private static readonly Dictionary<string, (string En, string Vi)> Lookup = Build();
    private static Dictionary<string, (string En, string Vi)> Build()
    {
        var lookup = new Dictionary<string, (string En, string Vi)>(StringComparer.Ordinal);
        foreach (var pair in Pairs)
        {
            lookup.TryAdd(pair.En, pair);
            lookup.TryAdd(pair.Vi, pair);
        }
        return lookup;
    }
    public static string Get(string? value, AppLanguage language) => value is null ? "" :
        Lookup.TryGetValue(value, out var pair) ? language == AppLanguage.Vi ? pair.Vi : pair.En : value;
}
